- id: ignition-perspective-lint
  name: Ignition Perspective Linter
  entry: ignition-lint
  language: python
  files: '\.json$'
  args: ['--format=text', '--severity=warning', '--exit-code']
  pass_filenames: true
  description: 'Lint Ignition Perspective component files for schema compliance and best practices'